version: '3'
services:
  grpcclient-product:
    image: anderjvila/grpcclient-product:v1.0.0-SNAPSHOT
    ports:
      - "8081:8080"
    environment:
      APP_PORT: "8080"
      GRPCSERVER_PRODUCT_ADDRESS: "host.docker.internal:9090"

networks:
  grpc-product-net:
    driver: bridge
