apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anderjvila-learning-store
  namespace: n-anderjvila-learning
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 100Mi
